---
tags: []
layout: input_bottom
editor: multiple_choice
type: problem
extra_visible: false
manual_evaluation: false
choices:
- value: Un MVP es ...
  checked: false
- value: Un MVP es ....
  checked: true
